### ISSUE TITLE
Need to handle exception for unconfigured box

### ISSUE THREAD

**Issue by digitronik** [digitronik/miqbox#16]
when we don't set downstream repository and try to pull image or check image we are getting error of improper url. we need to handle this with proper msg.

```
Version: (5.8, 5.9, 5.10, 5.11) [5.11]: 5.10
Traceback (most recent call last):
  File "/home/ndhandre/Projects/miqbox/env/bin/miqbox", line 11, in <module>
    load_entry_point('miqbox', 'console_scripts', 'miqbox')()
  File "/home/ndhandre/Projects/miqbox/env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ndhandre/Projects/miqbox/env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ndhandre/Projects/miqbox/env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ndhandre/Projects/miqbox/env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ndhandre/Projects/miqbox/env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ndhandre/Projects/miqbox/env/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/ndhandre/Projects/miqbox/env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ndhandre/Projects/miqbox/miqbox/miqbox.py", line 530, in images
    for img in get_repo_img(url=url, extension=extension):
  File "/home/ndhandre/Projects/miqbox/miqbox/miqbox.py", line 208, in get_repo_img
    page = requests.get(url, verify=ssl_verify).text
  File "/home/ndhandre/Projects/miqbox/env/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ndhandre/Projects/miqbox/env/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ndhandre/Projects/miqbox/env/lib/python3.7/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/home/ndhandre/Projects/miqbox/env/lib/python3.7/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/ndhandre/Projects/miqbox/env/lib/python3.7/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/home/ndhandre/Projects/miqbox/env/lib/python3.7/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None/builds/cfme/5.10/stable': No schema supplied. Perhaps you meant http://None/builds/cfme/5.10/stable?```

**Comment by digitronik** [comment]
fixed in #17
